---
title: "Untitled"
author: "Erik Olsson"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(readxl)
library(ggplot2)
library(janitor)
```

```{r}
data <- read_excel("SAFAD OR Footprints per Food.xlsx") %>% clean_names()


min_kost <- c(
  "Beef meat (Bos spp.)",
  "Chicken meat (Gallus domesticus)",
  "Pork / piglet meat (Sus scrofa)",
  "Turkey meat (Meleagris gallopavo)",
  "Elk meat (Alces alces)",
  "Mixed beef and pork meat",
  "Ham, pork",
  "Ham, turkey",
  "Bacon",
  "Salsiccia",
  "Cooked smoked sausage",
  "Grillkorv (common Swedish sausage)",
  "Falukorv (common Swedish sausage)",
  "Chorizo",
  "Textured soy protein",
  "Cooked Ham, Pork",
  "Bulgur wheat",
  "Rice",
  "Couscous",
  "Noodle, rice",
  "Noodle, wheat flour, with eggs",
  "Pasta, wheat flour, with eggs",
  "Muesli, no added sugar",
  "Main-crop potatoes",
  "Sweet potatoes (Ipomoea batatas)",
  "Cow milk, 1 - 2.9% fat (semi-skimmed milk)",
  "Cream 40 % fat",
  "Quark",
  "Cheese, Gouda",
  "Cheese, Grana Padano",
  "Lentils (Lens culinaris syn. L. esculenta)",
  "Beans (Phaseolus vulgaris)",
  "Egg white, chicken",
  "Egg yolk, chicken"
)



min_kost_data <- data %>%
  filter(name %in% min_kost)

# factor levels
min_kost_data$l1_category <- factor(
  min_kost_data$l1_category,
  levels = c("Starchy roots and tubers", "Grains and grain-based products", "Legumes, nuts and oilseeds", "Meat and meat products (including edible offal)", "Milk and dairy products")
)

min_kost_data$name <- factor(
  min_kost_data$name,
  levels = min_kost_data$name[order(min_kost_data$l1_category)]
)

ggplot(min_kost_data, aes(x = name, y = carbon_footprint_total_kg_co2e, color = l1_category)) +
  geom_point(size = 4) +
  theme_classic() +
  labs(y = "carbon_footprint_total_kg_co2e") +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    axis.title.x = element_blank(),  # removes x-axis label
    legend.position = "none"         # removes legend
  )+
  scale_color_manual(values = c(
    "Legumes, nuts and oilseeds" = "orange",
    "Meat and meat products (including edible offal)" = "firebrick",
    "Grains and grain-based products" = "goldenrod",
    "Starchy roots and tubers" = "forestgreen",
    "Milk and dairy products" = "steelblue"
  ))
  




```

