---
title: "Untitled"
author: "Erik Olsson"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(quantmod)
library(zoo)

# Example: Apple stock (AAPL)
stock_list <- c("NVDA", "MSFT" , "AAPL", "^GSPC", "SPOT")
getSymbols(stock_list, src = "yahoo", from = "1980-01-01", to = Sys.Date())
df_AAPL <- data.frame(Date = index(AAPL), coredata(AAPL))
df_SPOT <- data.frame(Date = index(SPOT), coredata(SPOT))
df_NVDA <- data.frame(Date = index(NVDA), coredata(NVDA))
head(df_AAPL)

rm_sw_AAPL <- rollmean(df_AAPL$AAPL.Close, k = 5, align = "right")  

rm_lw_AAPL <- rollmean(df_AAPL$AAPL.Close, k = 20, align = "right")

# add the MA vectors as columns in df
df_AAPL <- df_AAPL%>%
  mutate(rm_sw = rollmean(df_AAPL$AAPL.Close, k = 5, align = "right", fill = NA),
         rm_lw = rollmean(df_AAPL$AAPL.Close, k = 20, align = "right", fill = NA))%>%
  drop_na()

bs_vector <- c()
for (i in 1:length(df_AAPL$AAPL.Close) ) {
  if( df_AAPL$rm_lw[i] > df_AAPL$rm_sw[i]){
    bs_vector[i] <- TRUE
  } else {bs_vector[i] <- FALSE
}
}


```

